# Conclusion
Throughout our analysis of Broadway data from 1990 to 2016, several key insights emerged--some which surprised us, some which were expected, and some which required deeper exploration. In analyzing the top grossing shows and their respective theatres, we learned that some of the most successful shows on Broadway have had their locations changed throughout their run (such as the Lion Kind), where as others remained in the same place the entire time (such as Wicked). When taking a look at the relationship between weekly gross revenue and attendance, we found that the linear relationship we expected was weaker than we assumed it would be. Further, we noticed interesting trends in the data leading us to infer that capacity limiting the attendance to certain shows will drive prices up and down accordingly. Additionally, in seeking to explore why musicals seem to yield more profit on the whole on Broadway, we learned that ticket prices of musicals and plays are fairly comparable, with only the stability of their trends differing. Furthermore, we learned that musicals tend to occupy larger venues compared to plays, and thus have the capacity to sell more tickets and as such earn the higher grosses they do, and we speculated as to why that might be the case from an economic viewpoint. Finally, in taking a closer look at the attendance records for the individual theatres, we learned that there is a clear delineation of when certain hit shows (such as Wicked in the Gershwin, or the Book of Mormon at the Eugene O'Neill) began running, as evidenced by a sustained jump in attendance to capacity ratio. All in all, while there is certainly more to be learned about Broadway from this data set, and while some of our initial questions from our proposal (eg. Tony award impacts) couldn't be explored with it, we felt we gained a lot of insight into the financial aspects of Broadway and its trends.