# Data
We are still undecided regarding which data set to explore, but have narrowed it down to two potential options. First is the broadway.csv dataset available on the CORGIS database project (linked here: https://corgis-edu.github.io/corgis/csv/broadway/). This dataset is in CSV file format, has 12 columns and {*****} rows, doesn’t seem to be updated very frequently (the data ends in 2016), and is quite thorough. This is the leading contender due to its completeness & accessibility. Furthermore, the dataset’s author is still reachable via email (we have yet to get a response at time of writing, though). 

Second involves extracting data from where the author of the prior dataset cites his data from, the Broadway League website itself (https://www.broadwayleague.com/research/grosses-broadway-nyc/#weekly_grosses). This would be done for some arbitrarily large number of weeks, adapting an approach described by Professor Robbins–using the rvest library, reading from html over and over again, and appending the data subsets into one large usable one. The raw data from the website is updated weekly, and is similarly thorough, but is much more tedious to extract. 
Upon manual inspection, there does not appear to be any formally “missing” values in the broadway.csv data set; however, the description of the data set by the compiler of the set itself mentions that any rows for which the “gross potential” could not be found or calculated had its “gross potential” value set to 0 as default. Barring extreme outliers such as weeks with 0 ticket sales, which we are under the impression is impossible, the 0 value should be unique to such rows with the absent value. Thus, we should be able to treat the data set as if all ‘na’ values were housed in the “gross potential” row and were replaced by 0.

## Description

## Missing value analysis
