# Introduction
The Broadway industry is a cornerstone of live entertainment, renowned for its artistic performances and creative experience. The industry has continually adapted and evolved in response to a changing world. Through this exploratory data analysis project, we hope to better understand the financial trends of plays, musicals, and other live shows playing on Broadway. In particular, we are interested in seeing the difference in financial performance of musicals compared to plays and other show types, the timeline of certain productions and how their length and other factors are impacted by gross revenue over time, the number of shows on a weekly basis, and more, as well as how the venue impacts sales and other factors. That being said, our analysis will not necessarily be confined to the aforementioned questions, as we fully plan to explore to the best of our ability any other burning questions that pop up during our analysis of the data (perhaps questions regarding revivals [shows that have been staged before, but are being re-staged and reshown by a different production and creative team] and the impact of Tony Awards on sales and longevity [data not found in the datasets we are considering using, but is readily available online and can be manually collected with citations if it is deemed important]).
